name: chatcore
description: A library for 0xchat-core implemented in dart for flutter
version: 0.1.0
homepage: https://github.com/0xchat-dev/0xchat-core

environment:
  sdk: '>=2.18.5 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  sqflite: ^2.0.0+3
  reflectable: ^3.0.1
  built_value_generator: any
  json_annotation: ^4.0.1
  nostr_core_dart:
    path: ../nostr-dart




