name: chatcore
description: A library for 0xchat-core implemented in dart for flutter
version: 0.1.0
homepage: https://github.com/0xchat-dev/0xchat-core

environment:
  sdk: '>=3.1.3 <4.0.0'

dev_dependencies:
  build_runner: ^2.4.9
  isar_generator: ^3.1.0+1
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  flutter:
    sdk: flutter
  sqflite_sqlcipher: ^3.1.0+1
  isar: ^3.1.0+1
  convert: ^3.1.1
  pointycastle: ^3.3.0
  decimal: ^2.3.3
  reflectable: ^4.0.5
  built_value_generator: any
  json_annotation: ^4.8.0
  http: ^1.0.0
  bolt11_decoder: ^1.0.2
  connectivity_plus: ^6.1.3
  nostr_core_dart:
    git:
      url: https://github.com/0xchat-app/nostr-dart.git
      ref: main
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  nostr_mls_package:
    git:
      url: https://github.com/0xchat-app/nostr-mls-package.git
      ref: main




