name: chatcore
description: A library for 0xchat-core implemented in dart for flutter
version: 0.1.0
homepage: https://github.com/0xchat-dev/0xchat-core

environment:
  sdk: '>=3.4.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.4.10
  lints: ^2.0.0
  test: ^1.16.0
  watcher: ^1.1.2

dependencies:
  flutter:
    sdk: flutter
  sqflite_sqlcipher: ^3.1.0+1
  
  # Isar database - Required for code generation (build_runner)
  # Even though isar_flutter_libs already includes isar as a dependency,
  # we need to explicitly declare it here to enable the generator functionality
  # for creating .g.dart files. DO NOT REMOVE this dependency.
  isar:
    git:
      url: https://github.com/wcat7/isar.git
      path: packages/isar
      ref: 4.0.3-fix
  isar_flutter_libs:
    git:
      url: https://github.com/wcat7/isar.git
      path: packages/isar_flutter_libs
      ref: 4.0.3-fix
  convert: ^3.1.1
  pointycastle: ^3.3.0
  decimal: ^2.3.3
  reflectable: ^4.0.5
  built_value_generator: any
  json_annotation: ^4.8.0
  http: ^1.0.0
  bolt11_decoder: ^1.0.2
  connectivity_plus: ^6.1.3
  nostr_core_dart:
    path: ../nostr-dart
  path_provider: ^2.1.3
  nostr_mls_package:
    path: ../nostr-mls-package
  bitchat_flutter_plugin:
    path: ../bitchat-flutter-plugin
